### ISSUE TITLE
Visuzalization Implementation

### ISSUE THREAD

**Issue by rirodrig07** [IBM-DS-CRC/T7T#18]
- [x] Define requirements of what is needed to be presented in Watson @marceventura  - 0%

- [ ] Implement Visualizations @Wata395 @Scotturbina  - 0%

**Comment by marceventura** [comment]
[PCR Automation Charts Needed.pdf](https://github.com/IBM-DS-CRC/T7T/files/1089853/PCR.Automation.Charts.Needed.pdf)
